# Generated by Django 5.2.1 on 2025-05-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ali', models.BigIntegerField(blank=True, null=True, verbose_name='ID ALI')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ali', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Данные AliExpress',
                'verbose_name_plural': 'Данные AliExpress',
            },
        ),
    ]
