# Generated by Django 5.2.1 on 2025-05-23 14:08

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkUpItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wildberries_mark_up', models.IntegerField(default=12, verbose_name='Наценка ВБ')),
                ('ozon_mark_up', models.IntegerField(default=12, verbose_name='Наценка ОЗОН')),
                ('yandex_mark_up', models.IntegerField(default=0, verbose_name='Наценка Yandex')),
                ('avito_mark_up', models.IntegerField(default=0, verbose_name='Наценка Авито')),
                ('aliexpress_mark_up', models.IntegerField(default=0, verbose_name='Наценка Али')),
            ],
            options={
                'verbose_name': 'Наценка',
                'verbose_name_plural': 'Наценки',
            },
        ),
        migrations.CreateModel(
            name='NameAdditionalAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_1C', models.UUIDField(editable=False, unique=True, verbose_name='UUID class_1C')),
                ('name_attribute', models.CharField(max_length=50, verbose_name='Название атрибута')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_1C', models.UUIDField(editable=False, unique=True, verbose_name='UUUID class_1C')),
                ('article_1C', models.CharField(max_length=255, verbose_name='Артикл 1С')),
                ('code_1C', models.CharField(max_length=255, unique=True, verbose_name='Код 1С')),
                ('data_version', models.CharField(max_length=30, verbose_name='DataVersion')),
                ('name', models.TextField(verbose_name='Наименование товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
            ],
        ),
        migrations.CreateModel(
            name='TypePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_1C', models.UUIDField(editable=False, unique=True, verbose_name='UUID class_1C')),
                ('type_price', models.CharField(max_length=50, verbose_name='Тип цены')),
                ('suffix', models.CharField(max_length=50, verbose_name='Навзание полей в Prices')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оптовая цена')),
                ('wholesale_price_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оптовая цена 2')),
                ('wholesale_price_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оптовая цена 3')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Розничная цена')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='ValueAdditionalAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_attribute', models.TextField(verbose_name='Значение атрибута')),
                ('attribute_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nameadditionalattributes')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_attributes', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('image', models.ImageField(upload_to=catalog.models.image_upload_path, verbose_name='Изображение')),
                ('filename', models.CharField(db_index=True, default='', max_length=255, verbose_name='Имя файла (без пути)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'unique_together': {('product', 'filename')},
            },
        ),
    ]
