# Generated by Django 5.2.1 on 2025-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_img_uuid',
            field=models.UUIDField(editable=False, null=True, verbose_name='UUUID main img'),
        ),
    ]
