# Generated by Django 5.2.1 on 2025-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video_instruction_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видеоинструкцию'),
        ),
    ]
