# Generated by Django 5.2.1 on 2025-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_video_instruction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FilePathField(blank=True, max_length=255, null=True, path='media/video', verbose_name='Видео инструкции'),
        ),
    ]
