# Generated by Django 5.2.1 on 2026-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Архив (нет в выгрузке 1С)'),
        ),
    ]
