# Generated by Django 5.2.1 on 2025-05-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255, verbose_name='Индификатор продавца')),
                ('wb_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID WB')),
                ('wb_barcode', models.BigIntegerField(blank=True, null=True, verbose_name='BARCODE WB')),
                ('wb_item_id', models.BigIntegerField(blank=True, null=True, verbose_name='ITEMS ID WB')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wb', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Данные WB',
                'verbose_name_plural': 'Данные WB',
            },
        ),
    ]
