# Generated by Django 5.2.1 on 2025-05-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ozon', 'Ozon'), ('wb', 'Wildberries')], max_length=100, unique=True, verbose_name='Название')),
                ('is_disabled', models.BooleanField(default=False, help_text='Полное отключение передачи остатков', verbose_name='Отключить')),
            ],
            options={
                'verbose_name': 'Управление маркетплейсом',
                'verbose_name_plural': 'Управление маркетплейсами',
            },
        ),
        migrations.CreateModel(
            name='OrderAli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1C', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа 1C')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
                ('id_contr', models.UUIDField(default='d6762066-f767-11ee-8088-00155d46f78e', editable=False)),
                ('id_patner', models.UUIDField(default='d63b5bb6-f767-11ee-8088-00155d46f78e', editable=False)),
                ('exchange_1c', models.BooleanField(default=False, verbose_name='Передано в 1С')),
                ('number_ali', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа Ali')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('family', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Заказ ALI',
                'verbose_name_plural': 'Заказы ALI',
            },
        ),
        migrations.CreateModel(
            name='OrderOzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1C', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа 1C')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
                ('id_contr', models.UUIDField(default='d6762066-f767-11ee-8088-00155d46f78e', editable=False)),
                ('id_patner', models.UUIDField(default='d63b5bb6-f767-11ee-8088-00155d46f78e', editable=False)),
                ('exchange_1c', models.BooleanField(default=False, verbose_name='Передано в 1С')),
                ('number_ozon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа Ozon')),
            ],
            options={
                'verbose_name': 'Заказ Ozon',
                'verbose_name_plural': 'Заказы Ozon',
            },
        ),
        migrations.CreateModel(
            name='DateTimeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(verbose_name='С')),
                ('datetime_to', models.DateTimeField(verbose_name='По')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='order.marketplacecontrol', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Отключение по дате',
                'verbose_name_plural': 'Отключения по датам',
            },
        ),
        migrations.CreateModel(
            name='ItemInOrderAli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=128, null=True)),
                ('form_price', models.UUIDField(null=True, verbose_name='Вид цены')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderali', verbose_name='Номер заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAvito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1C', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа 1C')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
                ('id_contr', models.UUIDField(default='d6762066-f767-11ee-8088-00155d46f78e', editable=False)),
                ('id_patner', models.UUIDField(default='d63b5bb6-f767-11ee-8088-00155d46f78e', editable=False)),
                ('exchange_1c', models.BooleanField(default=False, verbose_name='Передано в 1С')),
                ('number_avito', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа авито')),
                ('name_advertisement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название объявления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_avito', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Заказ Авито',
                'verbose_name_plural': 'Заказы Авито',
            },
        ),
        migrations.CreateModel(
            name='ItemInOrderAvito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=128, null=True)),
                ('form_price', models.UUIDField(null=True, verbose_name='Вид цены')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('name_advertisement_item', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название объявления')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderavito', verbose_name='Номер заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemInOrderOzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=128, null=True)),
                ('form_price', models.UUIDField(null=True, verbose_name='Вид цены')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderozon', verbose_name='Номер заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderWB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1C', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа 1C')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
                ('id_contr', models.UUIDField(default='d6762066-f767-11ee-8088-00155d46f78e', editable=False)),
                ('id_patner', models.UUIDField(default='d63b5bb6-f767-11ee-8088-00155d46f78e', editable=False)),
                ('exchange_1c', models.BooleanField(default=False, verbose_name='Передано в 1С')),
                ('number_WB', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа WB')),
                ('object_id', models.CharField(max_length=128, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Заказ WB',
                'verbose_name_plural': 'Заказы WB',
            },
        ),
        migrations.CreateModel(
            name='WeeklyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time_from', models.TimeField(verbose_name='С времени')),
                ('time_to', models.TimeField(verbose_name='До времени')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rules', to='order.marketplacecontrol', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Отключение по дню недели',
                'verbose_name_plural': 'Отключения по дням недели',
            },
        ),
    ]
