# Generated by Django 5.2.1 on 2025-05-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderYM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1C', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа 1C')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма')),
                ('id_contr', models.UUIDField(default='d6762066-f767-11ee-8088-00155d46f78e', editable=False)),
                ('id_patner', models.UUIDField(default='d63b5bb6-f767-11ee-8088-00155d46f78e', editable=False)),
                ('exchange_1c', models.BooleanField(default=False, verbose_name='Передано в 1С')),
                ('number_ym', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа SberMarket')),
                ('status_sm', models.BooleanField(default=True, verbose_name='Статус на SberMarket')),
            ],
            options={
                'verbose_name': 'Заказ YaMarket',
                'verbose_name_plural': 'Заказы YaMarket',
            },
        ),
        migrations.CreateModel(
            name='ItemInOrderYM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=128, null=True)),
                ('form_price', models.UUIDField(null=True, verbose_name='Вид цены')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderym', verbose_name='Номер заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
