# Generated by Django 5.2.1 on 2025-05-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderym_iteminorderym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderym',
            name='status_sm',
        ),
    ]
