# Generated by Django 5.2.1 on 2025-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderym_status_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderym',
            name='number_ym',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа YaMarket'),
        ),
    ]
